### PR TITLE
adding javascript file

### PR DESCRIPTION
**Pull request by excel61**
the js file addes subcategories to the JavaScript link on the page. The links are created dynamically to practice different methods. The target pages are going to be prepared in a couple of days

### CODE REVIEW

**Comment by excel61** [comment]
The a tags wasn't closed with </a>
so when i removed the href of the list item(JavaScript), it still had link to the target page. 
I needed to remove the href so it can can show the subcategories (angular, vue, jQury) when it was clicked

**Comment by SamirJouni** [comment]
There seems to be a conflict, please resolve your conflict by syncing up your fork to the original repo: https://help.github.com/articles/syncing-a-fork/

And remember to pull before you push.
Good Luck !

**Comment by excel61** [comment]
thanks a lot. 
I switched to the master branch, then synced the fork. 
then went to new branch (addingJSfile) and performed (pull, add, commit, push)
but the "Compare & pull request" didn't show up on my page. 
did i do it wrong, what should id do now?
(thanks in advanced)

**Comment by excel61** [comment]
traying again

**Comment by SamirJouni** [comment]
```
<<<<<<< addingJSfile
          <h2>The employable skills in 2018:</h2>
          <ul>
          	<li class="skills"><img src="https://www.w3.org/html/logo/downloads/HTML5_Badge_512.png" alt="HTML 5"><a href="https://www.w3schools.com/html/html5_intro.asp"> HTML 5 </a> </li>
                <li class="skills"><img src="https://juststickers.in/wp-content/uploads/2014/05/CSS3-Mark-Shape-Cut.png" alt="CSS 3"><a href="https://www.w3schools.com/css/"> CSS 3</a></li>
                <li class="skills"><img src="https://img7.apk.tools/150/7/b/5/me.tuple.sassreference.png" alt="SASS"><a href="https://sass-lang.com/guide"> SASS</a></li>
                <li class="skills"><img src="https://upload.wikimedia.org/wikipedia/commons/thumb/e/ea/Boostrap_logo.svg/440px-Boostrap_logo.svg.png" alt="Bootstrap 4"><a href="https://www.w3schools.com/bootstrap4/"> Bootstrap 4</a> </li>
                <li class="skills" id="javascript" onclick="javaScriptCategorySelected()"><img src="https://www.easyprogramming.net/logo/js.png" alt="JavaScript/"> JavaScript </a></li>
=======
            <h2>The employable skills in 2018:</h2>
            <ul>
                <li class="skills"><img src="https://www.w3.org/html/logo/downloads/HTML5_Badge_512.png" alt="HTML 5"><a href="https://www.w3schools.com/html/html5_intro.asp"> HTML 5 </li>
                <li class="skills"><img src="https://juststickers.in/wp-content/uploads/2014/05/CSS3-Mark-Shape-Cut.png" alt="CSS 3"><a href="https://www.w3schools.com/css/"> CSS 3</li>
                <li class="skills"><img src="https://img7.apk.tools/150/7/b/5/me.tuple.sassreference.png" alt="SASS"><a href="https://sass-lang.com/guide"> SASS</li>
                <li class="skills"><img src="https://upload.wikimedia.org/wikipedia/commons/thumb/e/ea/Boostrap_logo.svg/440px-Boostrap_logo.svg.png" alt="Bootstrap 4"><a href="https://www.w3schools.com/bootstrap4/"> Bootstrap 4 </li>
                <li class="skills"><img src="https://www.easyprogramming.net/logo/js.png" alt="javascript"><a href="https://www.w3schools.com/js/"> Javascript </li>
>>>>>>> master
```

That's what your conflict looks like.

**Comment by SamirJouni** [comment]
You need to update your fork, then reorder the code in a way that doesn't break, where it is also not conflicting. (since someone else added code where you did. but they did it before you and you didn't update your fork with the changes.) Once fixed, you can get rid of the conflict markers and any duplicate code. And you should be good ! :)

**Comment by excel61** [comment]
This time it says there's no conflict

**Pull request merged**
